name: Build and Release on Tag

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Run Build
      run: npm run build

    - name: Commit dist folder
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add dist/
        git commit -m "Add dist folder"
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
        directory: dist

    - name: Extract Tag Name
      id: tag_name
      run: echo "::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/})"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_name.outputs.tag }}
        release_name: Release ${{ steps.tag_name.outputs.tag }}
        draft: false
        prerelease: false

    - name: Upload light-entity-card.js to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/light-entity-card.js
        asset_name: light-entity-card.js
        asset_content_type: application/javascript
