name: Build and Release on Tag

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Run Build
      run: npm run build

    - name: Create Release and upload light-entity-card.js
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.ref_name }}
        generate_release_notes: true
        files: dist/light-entity-card.js
